modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ZestyBlaze/Sculktech/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/ZestyBlaze/Sculktech/refs/heads/1.21.4-neo/update.json"
displayURL="https://github.com/ZestyBlaze/Sculktech"
#logoFile="examplemod.png" #optional

credits="Starsetcord for giving me the ideas for this abomination of a mod"
authors="${mod_authors}" #optional
description='''${mod_description}'''

#[[mixins]]
#config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"